# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpcCalc.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'grpcCalc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0egrpcCalc.proto\x12\x0b\x63\x61lculadora\"!\n\x10ResultadoInteiro\x12\r\n\x05valor\x18\x01 \x01(\x05\"/\n\nArgumentos\x12\x10\n\x08primeiro\x18\x01 \x01(\x05\x12\x0f\n\x07segundo\x18\x02 \x01(\x05\"\'\n\x0fOperacaoDecimal\x12\t\n\x01\x61\x18\x01 \x01(\x02\x12\t\n\x01\x62\x18\x02 \x01(\x02\"%\n\x10ResultadoDecimal\x12\x11\n\tresultado\x18\x01 \x01(\x02\x32\xb7\x02\n\x12\x43\x61lculadoraService\x12\x44\n\x05Somar\x12\x1c.calculadora.OperacaoDecimal\x1a\x1d.calculadora.ResultadoDecimal\x12G\n\x08Subtrair\x12\x1c.calculadora.OperacaoDecimal\x1a\x1d.calculadora.ResultadoDecimal\x12J\n\x0bMultiplicar\x12\x1c.calculadora.OperacaoDecimal\x1a\x1d.calculadora.ResultadoDecimal\x12\x46\n\x07\x44ividir\x12\x1c.calculadora.OperacaoDecimal\x1a\x1d.calculadora.ResultadoDecimalb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpcCalc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RESULTADOINTEIRO']._serialized_start=31
  _globals['_RESULTADOINTEIRO']._serialized_end=64
  _globals['_ARGUMENTOS']._serialized_start=66
  _globals['_ARGUMENTOS']._serialized_end=113
  _globals['_OPERACAODECIMAL']._serialized_start=115
  _globals['_OPERACAODECIMAL']._serialized_end=154
  _globals['_RESULTADODECIMAL']._serialized_start=156
  _globals['_RESULTADODECIMAL']._serialized_end=193
  _globals['_CALCULADORASERVICE']._serialized_start=196
  _globals['_CALCULADORASERVICE']._serialized_end=507
# @@protoc_insertion_point(module_scope)
