# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import grpcCalc_pb2 as grpcCalc__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in grpcCalc_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CalculadoraServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Somar = channel.unary_unary(
                '/calculadora.CalculadoraService/Somar',
                request_serializer=grpcCalc__pb2.OperacaoDecimal.SerializeToString,
                response_deserializer=grpcCalc__pb2.ResultadoDecimal.FromString,
                _registered_method=True)
        self.Subtrair = channel.unary_unary(
                '/calculadora.CalculadoraService/Subtrair',
                request_serializer=grpcCalc__pb2.OperacaoDecimal.SerializeToString,
                response_deserializer=grpcCalc__pb2.ResultadoDecimal.FromString,
                _registered_method=True)
        self.Multiplicar = channel.unary_unary(
                '/calculadora.CalculadoraService/Multiplicar',
                request_serializer=grpcCalc__pb2.OperacaoDecimal.SerializeToString,
                response_deserializer=grpcCalc__pb2.ResultadoDecimal.FromString,
                _registered_method=True)
        self.Dividir = channel.unary_unary(
                '/calculadora.CalculadoraService/Dividir',
                request_serializer=grpcCalc__pb2.OperacaoDecimal.SerializeToString,
                response_deserializer=grpcCalc__pb2.ResultadoDecimal.FromString,
                _registered_method=True)


class CalculadoraServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Somar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subtrair(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Multiplicar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Dividir(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CalculadoraServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Somar': grpc.unary_unary_rpc_method_handler(
                    servicer.Somar,
                    request_deserializer=grpcCalc__pb2.OperacaoDecimal.FromString,
                    response_serializer=grpcCalc__pb2.ResultadoDecimal.SerializeToString,
            ),
            'Subtrair': grpc.unary_unary_rpc_method_handler(
                    servicer.Subtrair,
                    request_deserializer=grpcCalc__pb2.OperacaoDecimal.FromString,
                    response_serializer=grpcCalc__pb2.ResultadoDecimal.SerializeToString,
            ),
            'Multiplicar': grpc.unary_unary_rpc_method_handler(
                    servicer.Multiplicar,
                    request_deserializer=grpcCalc__pb2.OperacaoDecimal.FromString,
                    response_serializer=grpcCalc__pb2.ResultadoDecimal.SerializeToString,
            ),
            'Dividir': grpc.unary_unary_rpc_method_handler(
                    servicer.Dividir,
                    request_deserializer=grpcCalc__pb2.OperacaoDecimal.FromString,
                    response_serializer=grpcCalc__pb2.ResultadoDecimal.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'calculadora.CalculadoraService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('calculadora.CalculadoraService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CalculadoraService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Somar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/calculadora.CalculadoraService/Somar',
            grpcCalc__pb2.OperacaoDecimal.SerializeToString,
            grpcCalc__pb2.ResultadoDecimal.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Subtrair(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/calculadora.CalculadoraService/Subtrair',
            grpcCalc__pb2.OperacaoDecimal.SerializeToString,
            grpcCalc__pb2.ResultadoDecimal.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Multiplicar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/calculadora.CalculadoraService/Multiplicar',
            grpcCalc__pb2.OperacaoDecimal.SerializeToString,
            grpcCalc__pb2.ResultadoDecimal.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Dividir(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/calculadora.CalculadoraService/Dividir',
            grpcCalc__pb2.OperacaoDecimal.SerializeToString,
            grpcCalc__pb2.ResultadoDecimal.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
