# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import grpc_mine_pb2 as grpc__mine__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in grpc_mine_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MineStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getTransactionId = channel.unary_unary(
                '/main.Mine/getTransactionId',
                request_serializer=grpc__mine__pb2.Empty.SerializeToString,
                response_deserializer=grpc__mine__pb2.NumResult.FromString,
                _registered_method=True)
        self.getChallenge = channel.unary_unary(
                '/main.Mine/getChallenge',
                request_serializer=grpc__mine__pb2.TxnId.SerializeToString,
                response_deserializer=grpc__mine__pb2.NumResult.FromString,
                _registered_method=True)
        self.getTransactionStatus = channel.unary_unary(
                '/main.Mine/getTransactionStatus',
                request_serializer=grpc__mine__pb2.TxnId.SerializeToString,
                response_deserializer=grpc__mine__pb2.NumResult.FromString,
                _registered_method=True)
        self.submitChallenge = channel.unary_unary(
                '/main.Mine/submitChallenge',
                request_serializer=grpc__mine__pb2.TaskRequest.SerializeToString,
                response_deserializer=grpc__mine__pb2.NumResult.FromString,
                _registered_method=True)
        self.getWinner = channel.unary_unary(
                '/main.Mine/getWinner',
                request_serializer=grpc__mine__pb2.TxnId.SerializeToString,
                response_deserializer=grpc__mine__pb2.NumResult.FromString,
                _registered_method=True)
        self.getSolution = channel.unary_unary(
                '/main.Mine/getSolution',
                request_serializer=grpc__mine__pb2.TxnId.SerializeToString,
                response_deserializer=grpc__mine__pb2.TaskResult.FromString,
                _registered_method=True)
        self.registerClient = channel.unary_unary(
                '/main.Mine/registerClient',
                request_serializer=grpc__mine__pb2.Empty.SerializeToString,
                response_deserializer=grpc__mine__pb2.NumResult.FromString,
                _registered_method=True)


class MineServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getTransactionId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getChallenge(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getTransactionStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def submitChallenge(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getWinner(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getSolution(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def registerClient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getTransactionId': grpc.unary_unary_rpc_method_handler(
                    servicer.getTransactionId,
                    request_deserializer=grpc__mine__pb2.Empty.FromString,
                    response_serializer=grpc__mine__pb2.NumResult.SerializeToString,
            ),
            'getChallenge': grpc.unary_unary_rpc_method_handler(
                    servicer.getChallenge,
                    request_deserializer=grpc__mine__pb2.TxnId.FromString,
                    response_serializer=grpc__mine__pb2.NumResult.SerializeToString,
            ),
            'getTransactionStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.getTransactionStatus,
                    request_deserializer=grpc__mine__pb2.TxnId.FromString,
                    response_serializer=grpc__mine__pb2.NumResult.SerializeToString,
            ),
            'submitChallenge': grpc.unary_unary_rpc_method_handler(
                    servicer.submitChallenge,
                    request_deserializer=grpc__mine__pb2.TaskRequest.FromString,
                    response_serializer=grpc__mine__pb2.NumResult.SerializeToString,
            ),
            'getWinner': grpc.unary_unary_rpc_method_handler(
                    servicer.getWinner,
                    request_deserializer=grpc__mine__pb2.TxnId.FromString,
                    response_serializer=grpc__mine__pb2.NumResult.SerializeToString,
            ),
            'getSolution': grpc.unary_unary_rpc_method_handler(
                    servicer.getSolution,
                    request_deserializer=grpc__mine__pb2.TxnId.FromString,
                    response_serializer=grpc__mine__pb2.TaskResult.SerializeToString,
            ),
            'registerClient': grpc.unary_unary_rpc_method_handler(
                    servicer.registerClient,
                    request_deserializer=grpc__mine__pb2.Empty.FromString,
                    response_serializer=grpc__mine__pb2.NumResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'main.Mine', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('main.Mine', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Mine(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getTransactionId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/main.Mine/getTransactionId',
            grpc__mine__pb2.Empty.SerializeToString,
            grpc__mine__pb2.NumResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getChallenge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/main.Mine/getChallenge',
            grpc__mine__pb2.TxnId.SerializeToString,
            grpc__mine__pb2.NumResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getTransactionStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/main.Mine/getTransactionStatus',
            grpc__mine__pb2.TxnId.SerializeToString,
            grpc__mine__pb2.NumResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def submitChallenge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/main.Mine/submitChallenge',
            grpc__mine__pb2.TaskRequest.SerializeToString,
            grpc__mine__pb2.NumResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getWinner(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/main.Mine/getWinner',
            grpc__mine__pb2.TxnId.SerializeToString,
            grpc__mine__pb2.NumResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getSolution(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/main.Mine/getSolution',
            grpc__mine__pb2.TxnId.SerializeToString,
            grpc__mine__pb2.TaskResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def registerClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/main.Mine/registerClient',
            grpc__mine__pb2.Empty.SerializeToString,
            grpc__mine__pb2.NumResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
