# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc_mine.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'grpc_mine.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fgrpc_mine.proto\x12\x04main\"\x1b\n\tNumResult\x12\x0e\n\x06result\x18\x01 \x01(\x05\"A\n\nTaskResult\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x10\n\x08solution\x18\x02 \x01(\t\x12\x11\n\tchallenge\x18\x03 \x01(\x05\"\x1e\n\x05TxnId\x12\x15\n\rtransactionId\x18\x01 \x01(\x05\"H\n\x0bTaskRequest\x12\x15\n\rtransactionId\x18\x01 \x01(\x05\x12\x10\n\x08\x63lientId\x18\x02 \x01(\x05\x12\x10\n\x08solution\x18\x03 \x01(\t\"\x07\n\x05\x45mpty2\xdc\x02\n\x04Mine\x12\x30\n\x10getTransactionId\x12\x0b.main.Empty\x1a\x0f.main.NumResult\x12,\n\x0cgetChallenge\x12\x0b.main.TxnId\x1a\x0f.main.NumResult\x12\x34\n\x14getTransactionStatus\x12\x0b.main.TxnId\x1a\x0f.main.NumResult\x12\x35\n\x0fsubmitChallenge\x12\x11.main.TaskRequest\x1a\x0f.main.NumResult\x12)\n\tgetWinner\x12\x0b.main.TxnId\x1a\x0f.main.NumResult\x12,\n\x0bgetSolution\x12\x0b.main.TxnId\x1a\x10.main.TaskResult\x12.\n\x0eregisterClient\x12\x0b.main.Empty\x1a\x0f.main.NumResultb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_mine_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NUMRESULT']._serialized_start=25
  _globals['_NUMRESULT']._serialized_end=52
  _globals['_TASKRESULT']._serialized_start=54
  _globals['_TASKRESULT']._serialized_end=119
  _globals['_TXNID']._serialized_start=121
  _globals['_TXNID']._serialized_end=151
  _globals['_TASKREQUEST']._serialized_start=153
  _globals['_TASKREQUEST']._serialized_end=225
  _globals['_EMPTY']._serialized_start=227
  _globals['_EMPTY']._serialized_end=234
  _globals['_MINE']._serialized_start=237
  _globals['_MINE']._serialized_end=585
# @@protoc_insertion_point(module_scope)
